[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5

[theme]
base = "dark"
primaryColor = "#00f0ff"
backgroundColor = "#050510"
secondaryBackgroundColor = "#0d0d1a"
textColor = "#dddddd"
font = "sans serif"

[browser]
gatherUsageStats = false
